---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

sui:
  validator:
    source_url: https://releases.sui.io
    ports:
      admin_interface_port: 1337
      metrics_port: 9184
      listen_address_port: 8084
      json_rpc_port: 9000
  fullnode:
    source_url: https://releases.sui.io
    ports:
      metrics_port: 9184
      json_rpc_port: 9000
      listen_address_port: 8084
  bridge:
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
