---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
monitor_bot_dns: bot.sui.mainnet.encapsulate.xyz
# ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

sui:
  validator:
    source_url: https://releases.sui.io
    ports:
      admin_interface_port: 1337
      network_address_port: 8080
      narwhal_primary_interface_port: 8081
      narwhal_worker_interface_port: 8082
      consensus_address_port: 8083
      p2p_port: 8084
      json_rpc_port: 9000
      metrics_port: 9184
  fullnode:
    source_url: https://releases.sui.io
    ports:
      admin_interface_port: 1337
      network_address_port: 8080
      narwhal_primary_interface_port: 8081
      narwhal_worker_interface_port: 8082
      consensus_address_port: 8083
      p2p_port: 8084
      json_rpc_port: 9000
      metrics_port: 9184
  bridge:
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
