---
# maintains ports, bianry or repo urls

org: encapsulate

default_node_types:
  - validator
  - default

sui:
  validator:
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
  fullnode:
    version: 88888888888
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
  bridge:
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
