---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
monitor_bot_dns: bot.sui.mainnet.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

sui:
  validator:
    source_url: https://releases.sui.io
    ports:
      prefix: 80
      suffix:
        admin: 37
        network: 80
        # Consensus port is updated through onchain transcation, After every epoch it reads onchain 
        # data and updates the port.
        consensus: 81
        p2p: 84
        rpc: 90
        metrics: 91
  fullnode:
    source_url: https://releases.sui.io
    ports:
      prefix: 80
      suffix:
        admin: 37
        network: 80
        consensus: 81
        p2p: 84
        rpc: 90
        metrics: 91
  bridge:
    source_url: https://releases.sui.io
    ports:
      server_listen_port: 9191
      metrics_port: 9186
