---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 8fc60f1fa966e90398c93beb67ad4f42992889c7
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: 8fc60f1fa966e90398c93beb67ad4f42992889c7
  bridge:
    version: 8fc60f1fa966e90398c93beb67ad4f42992889c7
  dummy:
    version: 8fc60f1fa966e90398c93beb67ad4f42992889c7
    external_address: dummy.sui.mainnet.encapsulate.xyz
