---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: b84aab31cc9342a38823ee96912a66b1a003c51e
    external_address: validator.sui.mainnet.encapsulate.xyz
  fullnode:
    version: b84aab31cc9342a38823ee96912a66b1a003c51e
  bridge:
    version: b84aab31cc9342a38823ee96912a66b1a003c51e
  dummy:
    version: b84aab31cc9342a38823ee96912a66b1a003c51e
    external_address: dummy.sui.mainnet.encapsulate.xyz
