---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 4e8aa9ee8b307b294cc85baf7d08af1f432e3d93
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 4e8aa9ee8b307b294cc85baf7d08af1f432e3d93
  bridge:
    version: 4e8aa9ee8b307b294cc85baf7d08af1f432e3d93
  dummy:
    version: 4e8aa9ee8b307b294cc85baf7d08af1f432e3d93
    external_address:
