---
# maintains versions and can overwrite all.yml
sui:
  validator:
    version: 6c3a7475b6fd4aea9b9f9443a6cfad01a135c036
    external_address: validator.sui.testnet.encapsulate.xyz
  fullnode:
    version: 6c3a7475b6fd4aea9b9f9443a6cfad01a135c036
  bridge:
    version: 6c3a7475b6fd4aea9b9f9443a6cfad01a135c036
  dummy:
    version: 6c3a7475b6fd4aea9b9f9443a6cfad01a135c036
    external_address:
