---
node_ufw_rules:
  validator:
    - port: "{{ sui.validator.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ sui.validator.ports.network_address_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: network_address_port

    - port: "{{ sui.validator.ports.narwhal_primary_interface_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: consensus_interface_port

    - port: "{{ sui.validator.ports.narwhal_primary_interface_port }}"
      proto: udp
      rule: allow
      from: any
      comment: narwhal_primary_interface_port

    - port: "{{ sui.validator.ports.narwhal_worker_interface_port }}"
      proto: udp
      rule: allow
      from: any
      comment: narwhal_worker_interface_port

    - port: "{{ sui.validator.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port

    - port: "{{ sui.validator.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_bot_dns }}"
      comment: metrics_port

  fullnode:
    - port: "{{ sui.fullnode.ports.p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ sui.fullnode.ports.network_address_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: protocol_transaction_interface_port

    - port: "{{ sui.fullnode.ports.narwhal_primary_interface_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: consensus_interface_port

    - port: "{{ sui.fullnode.ports.narwhal_primary_interface_port }}"
      proto: udp
      rule: allow
      from: any
      comment: narwhal_primary_interface_port

    - port: "{{ sui.fullnode.ports.narwhal_worker_interface_port }}"
      proto: udp
      rule: allow
      from: any
      comment: narwhal_worker_interface_port

    - port: "{{ sui.fullnode.ports.json_rpc_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: json_rpc_port

    - port: "{{ sui.fullnode.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port
