---
node_ufw_rules:
  validator:
    - port: "{{ p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ interface_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: interface_port

    - port: "{{ consensus_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: consensus_port

    - port: "{{ metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port

    - port: "{{ metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_bot_dns }}"
      comment: metrics_port

  fullnode:
    - port: "{{ p2p_port }}"
      proto: udp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ interface_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: protocol_transaction_interface_port

    - port: "{{ rpc_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: rpc_port

    - port: "{{ metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port
