---
# maintains file name, binary names, and anything which is not a diretcory or path

# HAProxy file names
haproxy_allowed_ips_file_name: allowed_ips.txt
haproxy_blocked_ips_file_name: blocked_ips.txt
haproxy_config_file_name: haproxy.cfg
