---
- name: Set project and service identifier in facts
  ansible.builtin.set_fact:
    project: "{{ group_names[0] }}"
    service_identifier: "{{ group_names[0] }}{{ '' if type in default_node_types else '-' + type }}"

- name: Set architecture variable based on system architecture
  ansible.builtin.set_fact:
    system_architecture: "{{ architecture_map[ansible_architecture] | default(ansible_architecture) }}"

- name: Display environment being deployed to
  ansible.builtin.debug:
    msg:
      - "Deploying to Host: {{ inventory_hostname }}"
      - "Groups: {{ group_names }}"
      - "Project: {{ project }}"
      - "Environment: {{ env }}"
      - "Type: {{ type }}"
      - "Version: {{ vars[project][type].version }}"
      - "Username: {{ service_identifier }}"
      - "Service Name: {{ service_identifier }}"
      - "Operating System: {{ ansible_system | lower }}"
      - "System Architecture: {{ system_architecture }}"

- name: Set all port variables dynamically
  ansible.builtin.set_fact:
    admin_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.admin }}"
    interface_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.interface }}"
    consensus_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.consensus }}"
    p2p_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.p2p }}"
    rpc_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.rpc }}"
    metrics_port: "{{ vars[project][type].ports.prefix ~ vars[project][type].ports.suffix.metrics }}"
  when: type == "validator" or type == "fullnode"

- name: Display all port variables
  ansible.builtin.debug:
    msg:
      - "P2P Port: {{ p2p_port }}"
      - "RPC Port: {{ rpc_port }}"
      - "Metrics Port: {{ metrics_port }}"
      - "Consensus Port: {{ consensus_port }}"
      - "Interface Port: {{ interface_port }}"
      - "Admin Port: {{ admin_port }}"
  when: type == "validator" or type == "fullnode"

- name: Confirm deployment details
  ansible.builtin.pause:
    seconds: 40

- name: Please confirm again
  ansible.builtin.debug:
    msg:
      - "Deploying to Host: {{ inventory_hostname }}"
      - "Project: {{ project }}"
      - "Environment: {{ env }}"
      - "Type: {{ type }}"

- name: Confirm deployment details
  ansible.builtin.pause:
    seconds: 20

- name: Include configure ufw task
  ansible.builtin.include_tasks: tasks/configure_ufw.yml
