---
# maintains directories and paths
bridge_home_dir: /opt/{{ service_identifier }}

bridge_bin_dir: "{{ bridge_home_dir }}/bin"
bridge_config_dir: "{{ bridge_home_dir }}/config"
bridge_data_dir: "{{ bridge_home_dir }}/data"
bridge_key_pairs_dir: "{{ bridge_home_dir }}/key-pairs"

bridge_directories:
  - "{{ bridge_home_dir }}"
  - "{{ bridge_bin_dir }}"
  - "{{ bridge_config_dir }}"
  - "{{ bridge_data_dir }}"
  - "{{ bridge_key_pairs_dir }}"

bridge_config_file_path: "{{ bridge_config_dir }}/{{ bridge_config_file_name }}"

bridge_authority_key_path: "{{ bridge_key_pairs_dir }}/{{ bridge_authority_key_file_name }}"
bridge_client_key_path: "{{ bridge_key_pairs_dir }}/{{ bridge_client_key_file_name }}"
