---
- name: Fetch the service binary
  ansible.builtin.get_url:
    url: "{{ vault.external.sui.sprivate_url }}/{{ sui[type].version }}/{{ node_service_default_binary_name }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
