---
- name: Include the ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules[type] }}"

- name: Include user creation task for sui
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Copy node configuration file
  ansible.builtin.template:
    src: "{{ env }}/{{ type }}/config.yaml.j2"
    dest: "{{ node_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Copy node genesis blob file
  ansible.builtin.copy:
    src: "{{ env }}/genesis.blob"
    dest: "{{ node_genesis_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch protocol key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_protocol_key_file_name }}"
        secret_destination_path: "{{ node_protocol_key_path }}"
        secret_type: key

    - name: Fetch worker key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_worker_key_file_name }}"
        secret_destination_path: "{{ node_worker_key_path }}"
        secret_type: key

    - name: Fetch network key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_network_key_file_name }}"
        secret_destination_path: "{{ node_network_key_path }}"
        secret_type: key

- name: Fetch binaries
  block:
    - name: Fetch the service binary
      ansible.builtin.get_url:
        url: "{{ sui[type].source_url }}/{{ sui[type].version }}/{{ node_service_default_binary_name }}"
        dest: "{{ node_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        force: true
        mode: "0755"
      notify:
        - Restart service

    - name: Fetch the cli binary
      ansible.builtin.get_url:
        url: "{{ sui[type].source_url }}/{{ sui[type].version }}/{{ node_cli_default_binary_name }}"
        dest: "{{ bridge_bin_dir }}/{{ node_cli_binary_name }}"
        owner: root
        group: root
        force: true
        mode: "0755"

- name: Copy sui general env file
  ansible.builtin.template:
    src: "{{ env }}/general.env.j2"
    dest: "{{ node_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Copy sui-node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
