---
bridge_ufw_rules:
    - port: "{{ sui.bridge.ports.server_listen_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: server_listen_port

    - port: "{{ sui.bridge.ports.metrics_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: metrics_port
