---
- name: Fetch the sui-tool binary
  ansible.builtin.get_url:
    url: "{{ sui[type].source_url }}/{{ sui[type].version }}/{{ snapshot_sync_tool_default_binary_name }}"
    dest: "{{ snapshot_sync_bin_dir }}/{{ snapshot_sync_tool_default_binary_name }}"
    owner: root
    group: root
    force: true
    mode: "0755"

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Delete data folder directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ snapshot_sync_authorities_data_dir }}"
    - "{{ snapshot_sync_consensus_data_dir }}"
  when: clean_database | default(false) | bool

- name: Create data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"
  loop:
    - "{{ snapshot_sync_authorities_data_dir }}"
    - "{{ snapshot_sync_consensus_data_dir }}"
  when: clean_database | default(false) | bool

- name: Download sui formal snapshot using sui-tool
  ansible.builtin.command:
    cmd: >
      {{ snapshot_sync_bin_dir }}/{{ snapshot_sync_tool_default_binary_name }} download-formal-snapshot --latest
      --genesis {{ snapshot_sync_genesis_file_path }}
      --network {{ env }}
      --path {{ snapshot_sync_authorities_data_dir }}
      --num-parallel-downloads 10
      --no-sign-request
  changed_when: false

- name: Set ownership of authorities data directory
  ansible.builtin.file:
    path: "{{ snapshot_sync_authorities_data_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
